version: '3'
services:
  spammer-db:
    image: postgres:12
    container_name: postgres12_6
    restart: always

    ports:
      - '5444:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: spammer-db
      PGDATA: /var/lib/postgresql/data/pgdata

    volumes:
      - spammer_postgres_sql:/var/lib/postgresql/data
      - /Users/vasylkorol/backaps:/var/opt/postgresql/backup


  pgadmin:
    image: dpage/pgadmin4
    container_name: spammer-db-pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: raj@nola.com
      PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  spammer_postgres_sql:
