spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:

    driver-class-name: org.postgresql.Driver
    dbcp2:
      default-schema: spammer-db

    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5444/spammer-db}
    username: postgres
    password: postgres

  mail:
    host: smtp.gmail.com
    port: 587
    username: ysellby@gmail.com
    password: ybrieqemhkqpjqxv
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    sender:
      email: no-reply@gmail.com
      text: no-reply


  mvc:
    hiddenmethod:
      filter:
        enabled: true
server:
  port: 8080
