
spring:

  mail:
    host: smtp.gmail.com
    port: 587
    username: ysellby@gmail.com
    password: ybrieqemhkqpjqxv
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    sender:
      email: no-reply@gmail.com
      text: no-reply


  mvc:
    hiddenmethod:
      filter:
        enabled: true
server:
  port: 8080
